YOLO:
    weights: '/content/yolo-crnn/yolo_weights.h5'
    table: '/content/yolo-crnn/txt.names'
    train:
        batch_size: 32
        img_path: './forms'
        imput_size: [640,480] #[w,h]
        tiny: True
        reduce_lr:
            monitor: 'loss'
            factor: 0.5
            patience: 1
            min_lr: 0.0001
            cooldown: 1
            verbose: 1

        tensorboard:
            update_freq: 'batch'
            histogram_freq: 1
            profile_batch: 0
    predict:
        iou_threshold: 0.3
        score_threshold: 0.25

CRNN:
    dataset_builder: &ds_builder
        wordsimg_path: './words'
        table: '/content/yolo-crnn/char.names'
        input_size: [28, null, 3]
        words_path: 'words.txt'
        num: 1000


    weights: '/content/yolo-crnn/crnn_weights.h5'
    train:
        dataset_builder:
            <<: *ds_builder

        valid_slipt: 0.4
        batch_size: 8
        learning_rate: 0.0001
        epochs: 100

        reduce_lr:
            monitor: 'val_loss'
            factor: 0.5
            patience: 2
            min_lr: 0.0001
            cooldown: 2
            verbose: 1

        tensorboard:
            histogram_freq: 1
            profile_batch: 0
YOLO_CRNN:
    file_path: "./forms"
    predict:
        iou_threshold: 0.3
        score_threshold: 0.25
        yolo_plot: False
        crnn_plot: False